name: CI with Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs: "blank" and "terraform"
  blank:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps for the "blank" job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps for the "terraform" job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Plan Terraform changes
      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      # Apply Terraform changes
      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
