name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to your preferred version

      - name: Initialize Terraform
        run: |
            cd terraform
            terraform init

      - name: Plan Terraform changes
        run: |
            cd terraform
             terraform plan -out=tfplan 
        env:
          TF_LOG: TRACE  # Set Terraform log level to get detailed output
      
      - name: Apply Terraform changes
        run: |
            cd terraform
             terraform apply -auto-approve tfplan
        env:
          TF_LOG: TRACE  # Set Terraform log level to get detailed output
